[package]
name = "markdown-compiler"
description = "A tiny markdown compiler"
version = "0.1.0"
authors = ["Julian Poma <poma.nob@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
